name: Sync with upstream

on:
  schedule:
    - cron: '0 0 * * *' # 每天同步一次
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: 'weijunext/indie-hacker-tools'  # 替换为原始仓库的地址
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes to fork
        run: |
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/typeyourc/indie-hacker-tools.git main  # 替换为你自己的仓库地址
